# Generated by Django 5.1.4 on 2024-12-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default2.jpg', upload_to='profile_pics'),
        ),
    ]
